import { TFeedSocketActions } from "../../types/feed";

export const CONNECTION_START: 'FEED/CONNECTION_START' = 'FEED/CONNECTION_START';
export const CONNECTION_SUCCESS: 'FEED/CONNECTION_SUCCESS' = 'FEED/CONNECTION_SUCCESS';
export const CONNECTION_ERROR: 'FEED/CONNECTION_ERROR' = 'FEED/CONNECTION_ERROR';
export const CONNECTION_CLOSED: 'FEED/CONNECTION_CLOSED' = 'FEED/CONNECTION_CLOSED';
export const GET_FEED: 'FEED/GET' = 'FEED/GET';

export const wsFeedActions: TFeedSocketActions = {
    wsInit: CONNECTION_START,
    onOpen: CONNECTION_SUCCESS,
    onClose: CONNECTION_CLOSED,
    onError: CONNECTION_ERROR,
    onMessage: GET_FEED,
};