import { TProfileOrdersSocketActions } from "../../types/profile-orders";

export const CONNECTION_START: 'PROFILE_ORDERS/CONNECTION_START' = 'PROFILE_ORDERS/CONNECTION_START';
export const CONNECTION_CLOSE: 'PROFILE_ORDERS/CONNECTION_CLOSE' = 'PROFILE_ORDERS/CONNECTION_CLOSE';
export const CONNECTION_SUCCESS: 'PROFILE_ORDERS/CONNECTION_SUCCESS' = 'PROFILE_ORDERS/CONNECTION_SUCCESS';
export const CONNECTION_ERROR: 'PROFILE_ORDERS/CONNECTION_ERROR' = 'PROFILE_ORDERS/CONNECTION_ERROR';
export const CONNECTION_CLOSED: 'PROFILE_ORDERS/CONNECTION_CLOSED' = 'PROFILE_ORDERS/CONNECTION_CLOSED';
export const GET_PROFILE_ORDERS: 'PROFILE_ORDERS/GET' = 'PROFILE_ORDERS/GET';

export const wsProfileOrdersActions: TProfileOrdersSocketActions = {
    wsInit: CONNECTION_START,
    wsClose: CONNECTION_CLOSE,
    onOpen: CONNECTION_SUCCESS,
    onClose: CONNECTION_CLOSED,
    onError: CONNECTION_ERROR,
    onMessage: GET_PROFILE_ORDERS,
};